version: "3.8"
services:
  server:
    build:
      context: "./"
      dockerfile: "./docker-files/nginx.dockerfile"
    ports:
      - '8000:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './backend:/var/www/html'
    depends_on:
      - php
      - mariadb
      - adminer
  php:
    build:
      context: "./"
      dockerfile: "./docker-files/php.dockerfile"
    volumes:
      - './backend:/var/www/html'
      - '/var/www/html/cache'
  mariadb:
    image: mariadb
    env_file: './env/mariadb.env'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  composer:
    build:
      context: "./"
      dockerfile: "./docker-files/composer.dockerfile"
    volumes:
      - './backend:/var/www/html/'

  npm:
    build:
      context: './'
      dockerfile: './docker-files/npm.dockerfile'
    volumes:
    - './frontend:/var/www/html/'

  frontend-dev:
    build:
      context: './'
      dockerfile: './docker-files/angular-dev.dockerfile'
    volumes:
      - './frontend:/var/www/html/'
      - '/var/www/html/node_modules'
    ports:
      - '4200:4200'
    tty: true
    stdin_open: true
